apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dgwp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dgwp
    app.kubernetes.io/part-of: tkwch-fix-0075-0073-app
  name: devfile-sample-dgwp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dgwp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dgwp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0073-tenant/tkwch-fix-0075-0073-app/devfile-sample-dgwp@sha256:5fa5363fb60b9e17648a16bd641cfdf0b8ea63e096021e27f967b0770b4f4cb9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
